backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: 'src/img/uploads'
public_folder: '/img/uploads'
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/index.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default.njk' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Navigation'
            name: 'eleventyNavigation'
            widget: 'object'
            collapsed: true
            fields:
              - { label: 'Key', name: 'key', type: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
